---
title: "Exploratory Data Analysis Template"
author: "Aidan Neher"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What is Exploratory Data Analysis?

Exploratory Data Analysis (EDA) is a structured approach for understanding your data that can be used for research question and hypothesis development. 

## Why Exploratory Data Analysis?

Overall Objective: Get insights to make better decisions. 

Sub-objectives include:

- Identify trends across time.
- Identify trends across space. 
- Identify and deal with outliers.
- Uncover patterns related to the response (a.k.a. target or dependent) variable of interest.
- Create research questions to explore or hypotheses to test.
- Identify possible new data sources.

Remark: Time and space are addressed separately to reduce the complexity.

## Mental models for getting started

EDA might sound intimidating to a data analysis newcomer. It certainly did to me. Thus, below are mental models that have helped me immensely.

- Wabi Sabi: Japanese world-view centered on the acceptance of transience and imperfection.
- Black Box Thinking: Focus on the data and your purpose throughout your project to avoid chasing shiny solutions.

[Source: Naked Data Science Podcast](https://open.spotify.com/show/4Sacw5UzY7utm6coTEHS0h?si=6e5ec050f22a4b85)

## Overview of the Data Analysis Process

1. Ask
2. Prepare
3. Process
4. Analyze - EDA is an analysis type.
6. Share
7. Act

[Source: Google Data Analytics Certificate](https://grow.google/certificates/data-analytics/)

## The Exploratory Data Analysis Process

1. Data Collection
2. Understanding Your Variables
3. Data Cleaning
4. Identify Correlated Variables
5. Choose Appropriate Statistical Methods
6. Visualize and Analyze Results
- Identify trends across time.
- Identify trends across space. 
- Identify and deal with outliers.
- Uncover patterns related to the response (a.k.a. target or dependent) variable of interest.
- Create research questions to explore or hypotheses to test.
- Identify possible new data sources.